export const DOG_BREEDS = [
  'Affenpinscher', 'Afghan Hound', 'Airedale Terrier', 'Akita', 'Alaskan Malamute',
  'American Eskimo Dog', 'American Staffordshire Terrier', 'Australian Cattle Dog',
  'Australian Shepherd', 'Australian Terrier', 'Basenji', 'Basset Hound', 'Beagle',
  'Belgian Malinois', 'Bernese Mountain Dog', 'Bichon Frise', 'Bloodhound',
  'Border Collie', 'Border Terrier', 'Borzoi', 'Boston Terrier', 'Boxer',
  'Brittany', 'Bull Terrier', 'Bulldog', 'Bullmastiff', 'Cairn Terrier',
  'Cavalier King Charles Spaniel', 'Chesapeake Bay Retriever', 'Chihuahua',
  'Chinese Shar-Pei', 'Chow Chow', 'Cocker Spaniel', 'Collie',
  'Colorado Mountain Dog', 'Dachshund', 'Dalmatian', 'Doberman Pinscher',
  'English Setter', 'English Springer Spaniel', 'French Bulldog',
  'German Shepherd', 'German Shorthaired Pointer', 'Giant Schnauzer',
  'Golden Retriever', 'Great Dane', 'Greyhound', 'Havanese', 'Irish Setter',
  'Italian Greyhound', 'Jack Russell Terrier', 'Labrador Retriever', 'Lhasa Apso',
  'Maltese', 'Mastiff', 'Miniature Pinscher', 'Miniature Schnauzer', 'Mixed Breed',
  'Newfoundland', 'Norwegian Elkhound', 'Old English Sheepdog', 'Papillon',
  'Pembroke Welsh Corgi', 'Pomeranian', 'Poodle', 'Portuguese Water Dog', 'Pug',
  'Rhodesian Ridgeback', 'Rottweiler', 'Saint Bernard', 'Samoyed',
  'Scottish Terrier', 'Shetland Sheepdog', 'Shih Tzu', 'Siberian Husky',
  'Soft Coated Wheaten Terrier', 'Staffordshire Bull Terrier', 'Standard Schnauzer',
  'Tibetan Terrier', 'Vizsla', 'Weimaraner', 'West Highland White Terrier',
  'Whippet', 'Wire Fox Terrier', 'Yorkshire Terrier',
]
